# Generated by Django 3.2.19 on 2023-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(0, 'Disponible'), (1, 'En arriendo'), (2, 'En mantenimiento')])),
            ],
        ),
    ]
